name: Validate

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      # https://nx.dev/getting-started/tutorials/typescript-packages-tutorial#create-a-ci-workflow
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build
